CREATE DATABASE ecobanhoapp;
USE ecobanhoapp;
DROP DATABASE ecobanho_app;

CREATE TABLE CHUVEIRO(
	ID_CHUVEIRO int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPO_CHUVEIRO VARCHAR(255) NOT NULL,
	VAZAO int NOT NULL
);

insert into chuveiro values (1,'ducha','123');
insert into chuveiro values (2,'eletrico','456');

delete from chuveiro
	where id_chuveiro = 1;


CREATE TABLE GRUPO(
	ID_GRUPO int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_GRUPO VARCHAR(255) NOT NULL,
	NUM_INTEGRANTES int NOT NULL	
);

insert into grupo values (1, 'teste', 4);
	UPDATE `grupo` SET `NOME_GRUPO` = 'Silva' WHERE `grupo`.`ID_GRUPO` = 1;
insert into grupo values (2, 'Santos', 3);


CREATE TABLE USUARIO(
	ID_USUARIO int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NICKNAME VARCHAR(255) NOT NULL,
	NOME_USUARIO VARCHAR(255) NOT NULL,
	SEXO BOOLEAN NOT NULL,
	TEMPO_USAL int NOT NULL,
	FK_TIPO_CHUVEIRO int NOT NULL,
	FK_ID_GRUPO int,

	FOREIGN KEY (FK_TIPO_CHUVEIRO) REFERENCES CHUVEIRO(ID_CHUVEIRO),
	FOREIGN KEY (FK_ID_GRUPO) REFERENCES GRUPO(ID_GRUPO)
);

insert into usuario values (1, 'NickTeste', 'marcos antonio', 0, 600, 1, 1);
	UPDATE `usuario` SET `NOME_USUARIO` = 'Marcos Antonio' WHERE `usuario`.`ID_USUARIO` = 1;

insert into usuario values (2, 'TestandoNick', 'Antonio Marcos', 0, 700, 2, 2);


delete from usuario
	where ID_USUARIO = 1;


CREATE TABLE BANHO(
	ID_BANHO int NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATA_BANHO DATE NOT NULL,
	TEMPO_REAL int NOT NULL,
	CONSUMO_REAL int NOT NULL,
	TEMPO_IDEAL int NOT NULL,
	CONSUMO_IDEAL int NOT NULL,
	ECONOMIA int NOT NULL,
	FK_USUARIO int NOT NULL,
	FK_CHUVEIRO int NOT NULL,

	FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(FK_CHUVEIRO) REFERENCES CHUVEIRO(ID_CHUVEIRO)
);

insert into banho values (1, '2019-01-01', 800, 123, 600, 123, 10, 1, 1);
insert into banho values (2, '2019-02-02', 700, 456, 600, 465, 15, 2, 2);









/* TESTE DE SELECT */


/*TESTE RANKING 2*/

SELECT GRUPO.ID_GRUPO
 AS ID_GRUPO, GRUPO.NOME _GRUPO,
 AS NOME_GRUPO, USUARIO.NOME_USUARIO
 AS USUARIO, SUM(BANHO.ECONOMIA)
 AS ECONOMIA

FROM USUARIO, GRUPO, BANHO

WHERE USUARIO.FK_ID_GRUPO = [ID_GRUPO] 
 AND BANHO.DATA_BANHO >= [DATA_INICIAL] 
 AND BANHO.DATA_BANHO <= [DATA_FINAL] 

ORDER BY ECONOMIA DESC;



/* TESTE RANKING 2*/


SELECT USUARIO.ID_USUARIO
 AS ID, USUARIO.NOME_USUARIO
 AS NOME, USUARIO.NICKNAME
 AS NICKNAME, BANHO.ECONOMIA
 AS ECONOMIA, BANHO.DATA_BANHO
 AS DATA
 
FROM USUARIO, BANHO

WHERE ID = [ID] 
 AND DATA >= [DATA_INICIAL] 
 AND DATA <= [DATA_FINAL] 

ORDER BY DATA;





SELECT USUARIO.ID_USUARIO
 AS ID, USUARIO.NOME_USUARIO
 
FROM USUARIO, BANHO

WHERE 

ORDER BY id_chuveiro;